# Introduction to Pandas

Pandas Use for Data Frame
Pandas is a Dataframe which handles tabular Data
What pandas can Help for Data Analyst--
1.handle missing Data(pd help to fill missing data)
2.columns can be inserted and deleted from the dataframe
3.data allingment(Series)
4.group by functions
5.pd+np
6.slicing & Indexing
7.joining & Merging
8.reshaping 
9.pandas can read excel file,csv file, html,.h5,pdf file
10.timeseries

Raw Data- The DataSet which Content missing Value is Called Raw Data
Clean Data- The DataSet which Does Not Content any missing Value is Called Clean Data

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

In [3]:
df=pd.read_csv(r'C:\Users\umari\Downloads\data.csv')

In [4]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [5]:
len(df) # Number of rows

195

In [6]:
id(df) # Memory address of the DataFrame

1991387638016

In [7]:
df.shape # Shape of the DataFrame (rows, columns)

(195, 5)

In [8]:
df.columns # List of column names

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [9]:
len(df.columns) # Number of columns

5

In [10]:
df.isnull() # Check for missing values

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [11]:
df.isnull().sum() # Count of missing values in each column

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [12]:
df.info() # Summary of the DataFrame including data types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB